### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by alphaleadership** [Derpinou/discord-tickets#1]
Ajouter la possibilité que envoyé un mp au bot ouvre un ticket

**Comment by Derpinou** [comment]
Discord-tickets est une librairie pour gérer les tickets, pour créer un ticket avec les mp du bots il suffit de faire une TicketManager#createTicket(...)
Si tu parlais d'une fonctionnalité ModMail, elle arrive bientôt ;)

**Comment by alphaleadership** [comment]
Oui

**Comment by alphaleadership** [comment]
Bien le modmail
